version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "admin", "--password", "admin@123", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin%40123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin@123
    depends_on:
      mongo:
        condition: service_healthy

  logger-service:
    build:
      context: ./packages/logger-service
      dockerfile: Dockerfile
    container_name: logger-service
    ports:
      - "8011:8011"
    environment:
      PORT: 8011
      MONGO_URI: mongodb://admin:admin%40123@mongo:27017/
      IS_LOCAL_LOGGING: "true"
      LOG_DIR: /logs
      IS_REMOTE_LOGGING: "true"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./logs:/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  auth-service:
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      IS_LOCAL_LOGGING: "true"
      LOG_DIR: /logs
      IS_REMOTE_LOGGING: "true"
      REMOTE_LOGGER_URL: "http://logger-service:8011/api/log"
      MONGO_URI: mongodb://admin:admin%40123@mongo:27017/
    depends_on:
      logger-service:
        condition: service_started
      mongo:
        condition: service_healthy
    volumes:
      - ./logs:/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  mongo_data:
